import java.io.*

object Generate {
    @JvmStatic
    fun main(args: Array<String>) {
        File("src/commonMain/kotlin/com/soywiz/kds/Stack.kt")
            .writeText(File("src/jvmTest/kotlin/StackTemplate.kt").readText().generateEspecified())
        File("src/commonMain/kotlin/com/soywiz/kds/Queue.kt")
            .writeText(File("src/jvmTest/kotlin/QueueTemplate.kt").readText().generateEspecified())
        File("src/commonMain/kotlin/com/soywiz/kds/Array2.kt")
            .writeText(File("src/jvmTest/kotlin/Array2Template.kt").readText().generateEspecified())
    }

    fun String.replaceTemplate(kind: String): String {
        val lkind = kind.toLowerCase()
        return this
            .replace("arrayListOf<T>", "${lkind}ArrayListOf")
            .replace("Array<T>", "${kind}Array")
            .replace(Regex("""(\w+)<T>""")) { kind + it.groupValues[1] }
            .replace(": T", ": $kind")
            .replace("-> T", "-> $kind")
            .replace("(T)", "($kind)")
            .replace("T, ", "$kind, ")
    }

    fun String.generateEspecified(): String {
        val text = this
        val intText = text.replaceTemplate("Int")
        val doubleText = text.replaceTemplate("Double")
        return "// File was autogenerated generated. Do not modify.\npackage com.soywiz.kds\n\n$text\n$intText\n$doubleText"
    }
}